Scholarship translations to ES and CA
RustFestEU/diversity-at-rustfest pull request #1
Opened 2019-08-16 18:59 UTC by angelmixu

Here are both translations, please, take a look for any typo, or rewording.

I'm not very fond of "si els nostres assistens necessiten un assitent"... but I can't think anything similar :_D

2019-08-16 21:10 UTC, alberss commented on 2019/scholarship-info.ca.md
> +Completant totes les nostres altres polítiques, un altra cop aquest any estem desenvolupant un programa de Beques per fer un cop de mà als nostres membres de la comunitat que necessiten ajudar per as
ojo aqui el TYPO , **qeu**

2019-08-16 21:13 UTC, alberss commented on 2019/scholarship-info.ca.md
> +Les despeses del biatje es poden fer servir per cobrir els viatje desde/fins a l'ambaixada (per la sol·licitut del visat) i a l'aeropot; adicionalment, per al transport local, menjar, medicació etc.
ojo aqui el TYPO, **biatge**

2019-08-16 21:13 UTC, alberss commented on 2019/scholarship-info.ca.md
> +**Ambdòs participants, tant els que hagin reservat personalment el biajte, o a través de la conferència,** tindran la possibilitat d'enviar les despeses després de la conferència per cobrir/reemborsa
typo **biatge**

2019-08-16 21:14 UTC, alberss commented on 2019/scholarship-info.ca.md
> +**Ambdòs participants, tant els que hagin reservat personalment el biajte, o a través de la conferència,** tindran la possibilitat d'enviar les despeses després de la conferència per cobrir/reemborsa
tambien **següents**

2019-08-16 21:14 UTC, alberss commented on 2019/scholarship-info.ca.md
> +- despeses de viatje i allotjament (reemborsament finbs el límit previst)
**fins**, se escapan letras del teclado jeje

2019-08-16 21:15 UTC, alberss commented on 2019/scholarship-info.ca.md
> +Les despeses del biatje es poden fer servir per cobrir els viatje desde/fins a l'ambaixada (per la sol·licitut del visat) i a l'aeropot; adicionalment, per al transport local, menjar, medicació etc.
ojo **biatje** otra vez

2019-08-16 21:21 UTC, alberss commented on 2019/scholarship-info.es.md
> +Las solicitudes se abrirán el 15 de agosto, y permanecerán abiertas hasta que todas las entradas hayan sido asignadas y el presupuesto exhaurido (pero almenos hasta el 15 de setiembre).
ep! exhaurido nop! es **agotado**

2019-08-16 21:21 UTC, alberss commented on 2019/scholarship-info.es.md
> +Empezaremos a contactar a los agraciados a principios de setiembre, aunque continuaremos asignando entradas contínuamente hasta setiembre u octubre, hasta que nuestro presuuesto se acabe. Todos los q
ojo que te sobra una U en **presupuesto**

2019-08-16 21:23 UTC, alberss commented on 2019/scholarship-info.es.md
> +Los gastos de viaje se pueden usar para cubrir el viaje desde/hacia la embajada (para la solicutud del visado) y al aeropuerto; adicionalmente, para el transporte local, comida, medicación etc. en Ba
resguardo del pago de la visa --> comprobande del pago del visado

2019-08-16 21:27 UTC, piny4man requested changes
Hay algunos cambios a realizar

2019-08-17 06:26 UTC, flaki commented
Hey folks, this looks amazing! Thank you for working late hours to get this out of the door, it's really much much appreciated!

Let me know when it all looks good and we can merge and I'll transition these over to the website and create the respective forms!

Thanks again!

2019-08-17 11:01 UTC, angelmixu commented on 2019/scholarship-info.ca.md
> +Completant totes les nostres altres polítiques, un altra cop aquest any estem desenvolupant un programa de Beques per fer un cop de mà als nostres membres de la comunitat que necessiten ajudar per as
arreglado!

2019-08-17 11:03 UTC, angelmixu commented on 2019/scholarship-info.ca.md
> +Les despeses del biatje es poden fer servir per cobrir els viatje desde/fins a l'ambaixada (per la sol·licitut del visat) i a l'aeropot; adicionalment, per al transport local, menjar, medicació etc.
fixed!

2019-08-17 11:05 UTC, angelmixu commented on 2019/scholarship-info.ca.md
> +**Ambdòs participants, tant els que hagin reservat personalment el biajte, o a través de la conferència,** tindran la possibilitat d'enviar les despeses després de la conferència per cobrir/reemborsa
hecho!

2019-08-17 11:06 UTC, angelmixu commented on 2019/scholarship-info.ca.md
> +- despeses de viatje i allotjament (reemborsament finbs el límit previst)
ya ves, y mira que me lo repasé... xD

2019-08-17 11:07 UTC, angelmixu commented on 2019/scholarship-info.ca.md
> +Les despeses del biatje es poden fer servir per cobrir els viatje desde/fins a l'ambaixada (per la sol·licitut del visat) i a l'aeropot; adicionalment, per al transport local, menjar, medicació etc.
joder... que sé que va con v... pero debo tener el dedo torcido xD

2019-08-17 11:12 UTC, angelmixu reviewed
I'd say I have fixed all the typos, we can probably merge now! :)

2019-08-17 11:15 UTC, angelmixu commented
@flaki I don't know how to set that the requested changes has been made, but you can merge it when you please :)

2019-08-17 11:16 UTC, merged